Mergue a develeop de Epic/10 pintado de gráficas y estudio de datos
TerryIsmael/decide-part-pacodelucia pull request #141
Opened 2023-12-14 15:56 UTC by Yuuta094

2023-12-15 14:47 UTC, JoseJavierAlcobendas requested changes
Tiene que pasar el codacy para que se pueda megear a develop y tambien estoy viendo que al hacerlo habria conflictos, soluciona todos esos problemas en una rama a partir del develop actual e introduce tus cambios con los comentarios anteriores.

2023-12-16 17:56 UTC, anglorcas approved these changes
its fixed

2023-12-16 19:51 UTC, JoseJavierAlcobendas approved these changes
Es correcto todo

2023-12-16 19:53 UTC, JoseJavierAlcobendas requested changes
hay conflictos con el loadtest/locustfile.py

2023-12-16 21:27 UTC, JoseJavierAlcobendas approved these changes

2023-12-16 21:27 UTC, merged